stages:
  - build
  - test
  - release
  - publish

test-web-service:
  stage: test
  image: registry.gitlab.com/medicines-discovery-catapult/informatics/docker-images/ci/golang:latest
  script:
    - go test -v ./... -coverpkg=./... -coverprofile=cover.out


lint:
  stage: test
  image: registry.gitlab.com/medicines-discovery-catapult/informatics/docker-images/ci/golang:latest
  script:
    - go mod tidy
    - go vet ./...
    - golangci-lint run
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/
  coverage: /total:\s+\(statements\)\s+(\d+.\d+\%)/

publish:
  stage: publish
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  before_script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --build-arg VERSION_HASH=$CI_COMMIT_SHORT_SHA --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  except:
    refs:
      - master
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

release:
  stage: release
  image: registry.gitlab.com/medicines-discovery-catapult/informatics/docker-images/ci/golang:latest
  script:
    - cictl exec release
  only:
    - main
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

publish-master:
  stage: publish
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  before_script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --build-arg VERSION_HASH=$CI_COMMIT_SHORT_SHA --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME --destination $CI_REGISTRY_IMAGE:latest
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/
