version: "3.6"
services:
  image-converter:
    volumes:
      - "./alex-crop-image:/opt/data"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8080 # if the external port is changed, this must also match the port in main_test.go

